@baseURL = http://localhost:3000

### Authenticate
# @name authenticate
POST  {{baseURL}}/auth HTTP/1.1
Content-Type: application/json

{
  "email": "jose@email.com",
  "password": "123456"
}

### Set Token
@authToken = {{authenticate.response.body.acessToken}}


### findAll
# @name RecadosController
GET {{baseURL}}/recados HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### findOne
GET {{baseURL}}/recados/1 HTTP/1.1
Content-Type: application/json

### create
POST  {{baseURL}}/recados HTTP/1.1
Content-Type: application/json

{
    "texto": "Recado",
    "deId": 1,
    "paraId": 2
}
### update
PATCH   {{baseURL}}/recados/20 HTTP/1.1
Content-Type: application/json

{
  "lido": true
}
### delete
DELETE {{baseURL}}/recados/20 HTTP/1.1
Content-Type: application/json

# @name PessoasController
### findAll
GET {{baseURL}}/pessoas/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

### findOne
GET {{baseURL}}/pessoas/2 HTTP/1.1
Content-Type: application/json

### create
POST  {{baseURL}}/pessoas HTTP/1.1
Content-Type: application/json

{
  "email": "jose@email.com",
  "nome": "Joao Sousa",
  "password": "123456"
}

### update
PATCH   {{baseURL}}/pessoas/6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "password": "123456"
}

### delete
DELETE {{baseURL}}/pessoas/1 HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json
